"""
Collects, organizes and filters recommendations generated by validators.
"""

from __future__ import annotations
from collections import defaultdict

from models.recommendation import (
    Recommendation,
    Severity,
)
from models.validation_result import ValidationResult


class RecommendationEngine:
    #manages validation recommendations and aggregates them
    def __init__(self) -> None:
        self._severity_order = {
            Severity.HIGH: 0,
            Severity.MEDIUM: 1,
            Severity.LOW: 2,
            "High": 0,
            "Medium": 1,
            "Low": 2,
        }
        self._recommendation_cache: dict[
            str,
            list[Recommendation],
        ] = {}

    def generate(
        self,
        review_id:str,
        validation_results: list[ValidationResult],
    ) -> list[Recommendation]:

        recommendations: list[Recommendation] = []

        for result in validation_results:
            recommendations.extend(
                result.recommendations
            )

        recommendations = self._remove_duplicates(
            recommendations
        )
        recommendations = self._sort_by_severity(
            recommendations
        )
        self.cache_recommendations(
            review_id,
            recommendations,
        )

        return recommendations

    def get_recommendation(
        self,
        recommendation_id: str,
        recommendations: list[Recommendation],
    ) -> Recommendation | None:

        for recommendation in recommendations:

            if recommendation.id == recommendation_id:
                return recommendation

        return None

    def get_recommendations(
        self,
        recommendation_ids: list[str],
        recommendations: list[Recommendation],
    ) -> list[Recommendation]:

        recommendation_map = {
            recommendation.id: recommendation
            for recommendation in recommendations
        }

        return [
            recommendation_map[recommendation_id]
            for recommendation_id in recommendation_ids
            if recommendation_id in recommendation_map
        ]

    def group_by_validator(
        self,
        recommendations: list[Recommendation],
    ) -> dict[str, list[Recommendation]]:

        grouped: dict[
            str,
            list[Recommendation],
        ] = defaultdict(list)

        for recommendation in recommendations:
            grouped[
                recommendation.validator
            ].append(
                recommendation
            )

        return dict(grouped)

    def group_by_category(
        self,
        recommendations: list[Recommendation],
    ) -> dict[str, list[Recommendation]]:

        grouped: dict[
            str,
            list[Recommendation],
        ] = defaultdict(list)

        for recommendation in recommendations:
            grouped[
                recommendation.category
            ].append(
                recommendation
            )

        return dict(grouped)

    def count_by_severity(
        self,
        recommendations: list[Recommendation],
    ) -> dict[str, int]:

        counts = {
            "High": 0,
            "Medium": 0,
            "Low": 0,
        }

        for recommendation in recommendations:
            severity= recommendation.severity

            if isinstance(
                severity,
                Severity
            ): 
                severity=severity.value
            else:
                counts[severity] +=1

        return counts

    def get_auto_fixable(
        self,
        recommendations: list[Recommendation],
    ) -> list[Recommendation]:

        return [
            recommendation
            for recommendation in recommendations
            if recommendation.auto_fixable
        ]

    def get_manual_fix(
        self,
        recommendations: list[Recommendation],
    ) -> list[Recommendation]:

        return [
            recommendation
            for recommendation in recommendations
            if not recommendation.auto_fixable
        ]

    def summary(
        self,
        recommendations: list[Recommendation],
    ) -> dict[str,int | float]:

        severity_count = self.count_by_severity(
            recommendations
        )

        return {
            "total": len(recommendations),
            "high": severity_count["High"],
            "medium": severity_count["Medium"],
            "low": severity_count["Low"],
            "auto_fixable": len(
                self.get_auto_fixable(
                    recommendations
                )
            ),
            "manual_fix": len(
                self.get_manual_fix(
                    recommendations
                )
            ),
        }
    
    def cache_recommendations(
            self,
            review_id:str,
            recommendations: list[Recommendation],
    ) -> None:
        self._recommendation_cache[
            review_id
        ] = recommendations

    def get_cached_recommendations(
            self,
            review_id:str,
    ) -> list[Recommendation]:
        return self._recommendation_cache.get(
            review_id,
            [],
        )
    
    def clear_cached_recommendations(
            self,
            review_id:str,
    ) -> None:
        self._recommendation_cache.pop(
            review_id,
            None,
        )

    def _remove_duplicates(
        self,
        recommendations: list[Recommendation],
    ) -> list[Recommendation]:

        unique: list[Recommendation] = []
        seen: set[tuple] = set()

        for recommendation in recommendations:
            key = (
                recommendation.validator,
                recommendation.category,
                recommendation.title,
                recommendation.line_number,
                recommendation.resource,
            )
            if key not in seen:
                seen.add(key)
                unique.append(recommendation)

        return unique

    def _sort_by_severity(
        self,
        recommendations: list[Recommendation],
    ) -> list[Recommendation]:

        return sorted(
            recommendations,
            key=lambda recommendation: (
                self._severity_order.get(
                    recommendation.severity,
                    99,
                ),
                recommendation.validator,
                recommendation.line_number
                if recommendation.line_number is not None
                else 0,
            ),
        )