"""
Defines the recommendation model used throughout the application.

Each validator generates recommendation objects for issues it detects.
The frontend displays these recommendations, allowing users to accept or reject them.
Only accepted recommendations are applied when generating the final reviewed Terraform file.
"""

from enum import Enum
from typing import Optional
from uuid import uuid4
from pydantic import BaseModel, Field, ConfigDict

class Severity(str, Enum):
    #Enum represents the severity levels of recommendations.
    HIGH = "High"
    MEDIUM = "Medium"
    LOW = "Low"

class RecommendationCategory(str, Enum):
    #Categories of recommendations based on the type of issue detected.
    SYNTAX = "Syntax"
    FORMATTING = "Formatting"
    SECURITY = "Security"
    CONFIGURATION = "Configuration"
    BEST_PRACTICE = "Best Practices"
    OPTIMIZATION = "Optimization"

class Recommendation(BaseModel):
    #Represents a single recommendation generated by a validator.

    model_config = ConfigDict(
        validate_assignment=True,
        use_enum_values=True,
        extra="forbid",
        frozen=False,
        json_schema_extra = {
            "example": {
                "id": "6f31d97e-8c3b-4f1a-9f2e-1c2b3d4e5f6a",
                "category":"Security",
                "severity":"High",
                "title":"Hardcoded Password",
                "message":"Replace hardcoded password with a Terraform variable.",
                "line_number": 12,
                "resource": "aws_db_instance.database",
                "original_value": "password= \"admin123\"",
                "suggested_value": "password = var.db_password",
                "auto_fixable": True,
                "validator": "SecurityValidator"
            }
        }
    )

    id:str = Field(
        default_factory=lambda: str(uuid4()), description="Unique recommendation ID."
    )

    category: RecommendationCategory = Field(
        ..., description= "Recommendation category."
    )

    severity: Severity = Field(
        ..., description= "Severity level."
    )

    title: str = Field(
        ..., description= "Short title describing the issue."
    )

    message: str = Field(
        ..., description= "Detailed explanation of the issue."
    )

    line_number: Optional[int] = Field(
        default=None,
        description="Line number where the issue occured."
    )

    resource: Optional[str] = Field(
        default=None,
        description= "Terraform resource associated with the issue."
    )

    original_value: Optional[str] = Field(
        default=None,
        description= "Original value detected"
    )

    suggested_value: Optional[str] = Field(
        default=None,
        description= "Suggested replacement value."
    )

    auto_fixable: bool = Field(
        default=False,
        description= "Whether this issue can be automatically fixed by the system."
    )

    validator: str = Field(
        ...,
        description = "Validator that generated the recommendation."
    )